### ISSUE TITLE
need more information on getting started

### ISSUE THREAD

**Issue by ian-p-cooke** [mcorbin/meuse#1]
Thanks for starting this project!  I wanted to experiment with what you have so far but am having trouble getting started.  I'm coming at this from the perspective of never having worked on a Clojure project.  Basically I'm looking for a 'from git clone to cargo publish' steps.  What I figured out so far:

* build uses https://leiningen.org/
    * sudo apt install leiningen
    * lein uberjar
        * produces target/uberjar/meuse-0.1.0-SNAPSHOT-standalone.jar
* depends on configuration file
    * example in dev/resources/config.yaml
    * passed in via environment variable
        * export meuse_configuration="/path/to/config.yml"
* run with java -jar target/uberjar/meuse-0.1.0-SNAPSHOT-standalone.jar

at this point it's up and running, I already have postgres running on my machine but didn't create the meuse user/schema.  I was expecting an exception when running meuse but it didn't so I figured I'd try and publish and that would tell me what I had to get working next.  However I haven't figured out what URL to use for the private registry.  Example:

in .cargo/config:

[registries]
icooke = { index = "http://dev-icooke:8855/what/goes/here" }

because every cargo api call results in:
`DEBUG [2019-05-02 05:08:02,479] manifold-pool-2-1 - meuse.http request  b561f5de-eb3d-4c7a-8692-dea6989b3d5c with subsystem :meuse.api.default with action :not-found`
   
so... do you have an example registries entry?

**Comment by mcorbin** [comment]
Hello,

Thank you for your interest in the project.
I added a `Run the project` section in the README. Let be know if you still have trouble running the project.

Regards,

**Comment by ian-p-cooke** [comment]
thanks!  I was able to publish to and read from meuse registry now.  I have some feedback that I'll open additional issues on.
