### ISSUE TITLE
Optimize frontend

### ISSUE THREAD

**Issue by Aloso** [mcorbin/meuse#14]
_Google Chrome Audits_ shows some problems:

### Performance

Fix these to speed up page loading for devices with a slow internet connection.

- [Enable text compression](https://developers.google.com/web/tools/lighthouse/audits/text-compression) (most important for static resources)
- [Remove unused CSS](https://developers.google.com/web/tools/lighthouse/audits/unused-css)
- [Serve static assets with an efficient cache policy](https://developers.google.com/web/tools/lighthouse/audits/cache-policy)

### Accessibility

- Background and foreground colors do not have a sufficient contrast ratio (all blue links)

### Best Practices

- Use HTTP/2
- jQuery 3.3.1 has a known security vulnerability

## How to fix

- Enable text compression, enable HTTP/2, set `Cache-control` header: There are probably options in the web framework, I don't know
- Unused CSS: This could be easily fixed by switching from CSS to [SASS](https://sass-lang.com/)
- Make links slightly darker
- Upgrade to jQuery 3.4

**Comment by mcorbin** [comment]
Thanks, I will take a look.

For HTTP2, Meuse currently uses https://github.com/ztellman/aleph as a web server, but I will maybe switch to [ring-jetty](https://github.com/ring-clojure/ring) in the future. I should verify if these servers support HTTP2 (or if it's not too difficult to fork them and add support for it).

**Comment by Aloso** [comment]
Question: Could you make a telegram/discord/slack group for contributing/asking questions?

**Comment by mcorbin** [comment]
> Question: Could you make a telegram/discord/slack group for contributing/asking questions?

I prefer to stick with Github issues for now. You can also reach me by email if you want.
