### ISSUE TITLE
Rejects version as non-semver

### ISSUE THREAD

**Issue by paulvt** [mcorbin/meuse#18]
I am trying to publish a crate with a semver-compatibile version, but Meuse rejects it:
```
   Uploading foo v7.0.0-alpha.4 (/path/to/foo)
error: api errors (status 200 OK): Wrong input parameters:
 - field vers: the value should be a valid semver string
```
Am I missing something here?
See also: https://semver.org/spec/v2.0.0.html#spec-item-9 (and the BNF at the bottom)

**Comment by mcorbin** [comment]
Hello,

You are right, Meuse only accepts `x.y.z` versions. I will try to fix that quickly and publish a new release.

Thanks you for the report.

**Comment by mcorbin** [comment]
I've released v0.4.2 (https://github.com/mcorbin/meuse/releases/tag/v0.4.2) which should fix this issue.
Can you tell me if it's ok for you ?

**Comment by paulvt** [comment]
Yes, I can upload the crates now. Thanks for the quick response!

(Btw, we deploy Meuse using Kubernetes and build an image for it using your `Dockerfile` (although it doesn't really build it, but ok). However, on release `Dockerfile` never gets a version bump, it is still at 0.2.0, so I'm keeping a local change for now.)

**Comment by mcorbin** [comment]
> (Btw, we deploy Meuse using Kubernetes and build an image for it using your Dockerfile (although it doesn't really build it, but ok). However, on release Dockerfile never gets a version bump, it is still at 0.2.0, so I'm keeping a local change for now.)

Good catch, I totally forgot this file.

I updated the Dockerfile to also build the jar. Also, the Dockerfile does not need the version anymore.
