### ISSUE TITLE
Database schema script not found

### ISSUE THREAD

**Issue by lanklaas** [mcorbin/meuse#20]
Hi,

I am following the installation guide and I want to run the schema script that is linked but the link returns 404:

https://github.com/mcorbin/meuse/blob/master/dev/resources/sql/schema.sql 

I got the link from here: https://meuse.mcorbin.fr/installation/requirements/

Where can I find it?

**Comment by mcorbin** [comment]
Hello,

I forgot to update this part of the documentation.

You don't need to create the database anymore, Meuse will handle database migrations automatically when it starts (cf https://meuse.mcorbin.fr/installation/configuration/#database-migrations). 

Sorry about that, I've updated the `requirements` page.
