### ISSUE TITLE
Show last token usage

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [mcorbin/meuse#27]
To use as private registry, and provide a great monitoring on access (very important because it store sources of code...), I think it can be awesome to add the last usage of the token.
It requires to update database, Rest API and UI.

**Comment by mcorbin** [comment]
Hello,

It should be easy to implement. I will try to take a look soon.

**Comment by mcorbin** [comment]
Done in https://github.com/mcorbin/meuse/commit/0293786baf82ca10968eab65ab01c4930efd82a4

The "list tokens" API call (https://meuse.mcorbin.fr/api/token/) will show you this information (I will update the doc later).
