### ISSUE TITLE
Bug after restart on docker, crate-index already exists

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [mcorbin/meuse#32]
Hello,

I have restarted the service, it won't restart as I have received that error:
```
destination path 'crate-index' already exists and is not an empty directory
```

Is it possible to fix that ?

Thank you !
Marc-Antoine

**Comment by mcorbin** [comment]
Hello,

Are you sure this error is returned by Meuse (and not by a script cloning the index for example) ?

**Comment by mcorbin** [comment]
@MarcAntoine-Arnaud Did you managed to fix this issue ?

**Comment by MarcAntoine-Arnaud** [comment]
Hello @mcorbin,

I have check locally and yes you've right, I have a small script to clone the git registry !

So it will fix it :D
Thank you
