### ISSUE TITLE
Crates with + in version return 404 via meuse

### ISSUE THREAD

**Issue by stefos-pd** [mcorbin/meuse#33]
Downloading a crate from meuse returns a 404 if the crate version contains a + sign.

tested with openssl-src,  flatc and a few other crates.

From crates.io the following works as expected:

curl -v -L "https://crates.io/api/v1/crates/flatc/0.1.0+1.12.0/download" -o tmpdl
curl -v -L "https://crates.io/api/v1/crates/openssl-src/111.10.1+1.1.1g/download" -o tmpdl

via meuse I get a 404 on:
curl -v -L "https://mirror.company.com/api/v1/mirror/flatc/0.1.0+1.12.0/download" -o tmpdl
curl -v -L "https://mirror.company.com/api/v1/mirror/openssl-src/111.10.1+1.1.1g/download" -o tmpdl

but 200 on:
curl -v -L "https://mirror.company.com/api/v1/mirror/unicase/2.6.0/download" -o tmpdl

So it seems that versions with a + are not working atm.

**Comment by martijndegouw** [comment]
The logs show the following message:
 meuse.api.default uri not found: :get /api/v1/mirror/flatc/0.1.0+1.12.0/download

**Comment by mcorbin** [comment]
Hello, thanks for the report. I will take a look.

**Comment by mcorbin** [comment]
I found the root cause (it's related to the library I use for routing), I will release a version with a fix during the evening.

**Comment by mcorbin** [comment]
The release https://github.com/mcorbin/meuse/releases/tag/v1.1.2 should fix the issue.

**Comment by stefos-pd** [comment]
This resolves the issue! Thanks for the super speedy fix 👍
