### ISSUE TITLE
token generation doesn't work through website's /me

### ISSUE THREAD

**Issue by ian-p-cooke** [mcorbin/meuse#37]
are there any plans on adding token generation through the front-end's /me URL?  That's a bit more friendly than using `curl`.  This is how cargo's help prompts a user to create a token.

**Comment by mcorbin** [comment]
Hello,

I do not plan do implement that for now, but I could easily modify the /me page to add the curl command on it.
I also plan to write a CLI to interact with Meuse to have something more user friendly than curl.
