### ISSUE TITLE
allowed-registries not used

### ISSUE THREAD

**Issue by ian-p-cooke** [mcorbin/meuse#4]
I forgot to put a 'allowed-registries' key to whitelist crates.io as described at https://github.com/rust-lang/rfcs/blob/master/text/2141-alternative-registries.md but meuse let me publish my crate with crates.io dependencies anyways.  I think it should have rejected my publish.

**Comment by mcorbin** [comment]
Good catch, I will try to fix this soon. Thanks  ;)

**Comment by mcorbin** [comment]
Meuse should now support the `allowed-registry` option.
If I try to publish a crate with a dependency to `crates.io`, Meuse returns: 

```
error: api errors (status 200 OK): the registry https://github.com/rust-lang/crates.io-index is not allowed
```

With `"allowed-registries": ["https://github.com/rust-lang/crates.io-index"]` in the config, it works.

**Comment by ian-p-cooke** [comment]
confirmed allowed-registries is used and can prevent crates-io dependencies.
