### ISSUE TITLE
configurable s3 key prefix?

### ISSUE THREAD

**Issue by jonathanstrong** [mcorbin/meuse#41]
I noticed that the code in `src/meuse/store/s3.clj` pretty uniformly includes a notion of a `prefix` that is appended to the beginning of the object key. However, the config specification in `src/meuse/spec.clj` does not include any option to specify a key prefix for s3 storage. 

Is the notion of `prefix` in the s3 storage code limited to prefixing keys by crate name and/or version? Or would it be possible to allow a configurable key prefix to be used, as a means of namespacing the s3 objects at smaller granularity than a bucket? 

In other words, would it be possible to change the spec to

```
(defmethod crate-store "s3"
  [_]
  (s/keys :req-un [:s3/access-key
                   :s3/secret-key
                   :s3/endpoint
                   :s3/bucket
                   :s3/key-prefix]))
```

... and then integrate the `s3/key-prefix` value into the key-generating code in `s3.clj`?

(I am not a clojure developer - asking to check whether I am missing something big about this. I would be happy to attempt to make the changes myself if this is a desirable change and you think it will be straightforward.)

One problem a configurable key prefix would create is if the prefix configuration were changed, after objects had already been written to s3 -- the current code would not be able to find those objects, would it?

Another possible solution would be to include the `crates_versions` id in the s3 key, which would at least guarantee unique object keys.

**Comment by mcorbin** [comment]
Hello,

Sorry for the late reply.

The s3 prefix is only used when mirroring crates.io for now (https://www.meuse.mcorbin.fr/installation/mirroring/). In that case I add the `.crates.io` prefix to crates names to be sure they do not conflict with other crates.

The setting is not exposed to end users so no one can configure it. As you said exposing it can be risky because if it's updated crates will be not found.

**Comment by jonathanstrong** [comment]
> In that case I add the .crates.io prefix to crates names to be sure they do not conflict with other crates.

Yes - this is the aspect I am interested in as well, otherwise two meuse instances could end up saving crates to the same s3 key.

> exposing it can be risky because if it's updated crates will be not found.

what do you think about using the id field/column from `crates_versions` table in database as the s3 key? that would guarantee unique path for every crate version. are there any downsides to that in terms of either performance (needing to fetch the id from database when the request path only contains a name) or otherwise? that might be simpler and less error prone than allowing a configurable prefix.

```sql
CREATE TABLE IF NOT EXISTS crates_versions(
id UUID PRIMARY KEY,
-- ...
crate_id UUID,
FOREIGN KEY (crate_id) REFERENCES crates(id)
);
```

**Comment by mcorbin** [comment]
I'm afraid it will create more complexity on the app for a small gain. 
The recommend way to manage multiple Meuse instances would be to have une bucket per instance.

**Comment by jonathanstrong** [comment]
reasonable enough - thanks for considering!
