### ISSUE TITLE
issues with Dockerfile upgrade to jdk:17

### ISSUE THREAD

**Issue by jonathanstrong** [mcorbin/meuse#42]
encountered this error message from running `$ docker build .`:

```console
Step 10/13 : RUN apt-get update && apt-get -y upgrade && apt-get install -y git
 ---> Running in 107a7a75fb08
/bin/sh: apt-get: command not found
```

It's confusing because the image it was using before (`openjdk:11`) did that step just fine, I guess they changed it.

I found another image, `openjdk:slim-bullseye` that works. "bullseye" is debian release code name. not sure if "slim" is worth much vs the fat one but it was the first one I got to work. 

Initially I tried to do `openjdk:17-alpine` but that had a lot of differences (`apk` vs `apt-get`, need to install `openssh`, different command line options for `useradd`/`groupadd` and I abandoned that effort).

**Comment by mcorbin** [comment]
Hello,

I pushed a new Dockerfile which now build successfully.

**Comment by jonathanstrong** [comment]
thanks!
