### ISSUE TITLE
can't not copy file from build stage

### ISSUE THREAD

**Issue by Sherlock-Holo** [mcorbin/meuse#43]
run `docker build -t meuse .`

it will fail on

> Step 8/13 : COPY --from=build-env /app/target/uberjar/meuse-*-standalone.jar /app/meuse.jar
> COPY failed: no source files were specified

**Comment by mcorbin** [comment]
Hello,

It works on my computer :s

**Comment by RoastVeg** [comment]
I can reproduce this issue on my machine. Looks like the output folder from `build-env` isn't as expected:
```
Created /app/target/default+uberjar/meuse-1.3.0.jar
Created /app/target/default+uberjar/meuse-1.3.0-standalone.jar
```

Versus the expected:
```
Step 8/13 : COPY --from=build-env /app/target/uberjar/meuse-*-standalone.jar /app/meuse.jar
COPY failed: no source files were specified
```

**Comment by dkales** [comment]
Also ran into this.

A fix is to call `lein uberjar` in the Dockerfile without the default profile.

```
RUN lein with-profile :uberjar uberjar
```
Or just fix up the COPY command to copy from `default+uberjar`, although idk how stable this is, since I don't know anymore than one can quickly google about the clojure/lein build process.

**Comment by mcorbin** [comment]
I modified the COPY path in the image, it should be good now.
